version: "3.9"
services:
  unittest:
    build:
      context: .
      dockerfile: Dockerfile.testing
    image: springio/my-movies-api-unittest
    environment:
      - API_PORT=8080 # Use constant port
      - SPRING_APPLICATION_NAME=${SPRING_APPLICATION_NAME}
      - LOGGING_LEVEL=OFF # Only show errors
  alltest:
    build:
      context: .
      dockerfile: Dockerfile.testing
    image: springio/my-movies-api-alltest
    networks:
      - db-net
    environment:
      - API_PORT=8080 # Use constant port
      - SPRING_APPLICATION_NAME=${SPRING_APPLICATION_NAME}
      - LOGGING_LEVEL=OFF # Only show errors
      - SPRING_DATASOURCE_URL_HOST=db # Internal connection to db
      - SPRING_DATASOURCE_URL_PORT=5432 # Internal port is always 5432
      - SPRING_DATASOURCE_URL_DB=${SPRING_DATASOURCE_URL_DB}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_TESTING_PROFILES_ACTIVE=daotest,applicationtest,integrationtest,systemtest

networks:
  db-net:
    name: dev-my-movies-network-db
    external: true